-- Add is_ai_generated column to lead_tags table
ALTER TABLE public.lead_tags 
ADD COLUMN IF NOT EXISTS is_ai_generated boolean NOT NULL DEFAULT false;

-- Add index for filtering by AI-generated tags
CREATE INDEX IF NOT EXISTS idx_lead_tags_is_ai_generated ON public.lead_tags(is_ai_generated);

-- Add unique constraint to prevent duplicate tags per lead
ALTER TABLE public.lead_tags 
ADD CONSTRAINT lead_tags_lead_tag_unique UNIQUE (lead_id, tag_text);

-- Add comment for documentation
COMMENT ON COLUMN public.lead_tags.is_ai_generated IS 'True if tag was auto-generated by AI, false if manually added by user';