-- Clear existing data and insert canonical vertical registry
DELETE FROM public.vertical_training;

-- Insert all 100 canonical verticals with proper JSONB casting
INSERT INTO public.vertical_training (rank, industry_name, parent_archetype, why_priority, pain_points, why_phone_ai_fits, where_to_find)
VALUES
-- CORE PHONE-AI VERTICALS (TOP 20 — LOCKED ORDER)
(1, 'Plumbing', NULL, '["High emergency volume", "24/7 demand", "Immediate booking need"]'::jsonb, '["Missed calls during jobs", "After-hours emergencies", "Scheduling chaos"]'::jsonb, '["Callers need immediate response", "Emergency triage critical", "Booking confirmation required"]'::jsonb, '["Google Maps", "HomeAdvisor", "Angi", "Thumbtack"]'::jsonb),
(2, 'HVAC', NULL, '["Seasonal peaks", "Emergency breakdowns", "Service agreements"]'::jsonb, '["Seasonal call spikes", "After-hours emergencies", "Technician scheduling"]'::jsonb, '["Emergency triage", "Appointment booking", "Service plan upsells"]'::jsonb, '["Google Maps", "HomeAdvisor", "HVAC contractor lists"]'::jsonb),
(3, 'Electricians', NULL, '["Emergency demand", "Safety-critical", "Licensing requirements"]'::jsonb, '["Emergency calls", "Estimate requests", "Permit questions"]'::jsonb, '["Safety triage", "Urgent scheduling", "Permit guidance"]'::jsonb, '["Google Maps", "Angi", "Electrician directories"]'::jsonb),
(4, 'Roofing', NULL, '["Storm damage peaks", "Insurance claims", "Large ticket sales"]'::jsonb, '["Storm surge calls", "Estimate scheduling", "Insurance coordination"]'::jsonb, '["Damage assessment intake", "Estimate booking", "Insurance info collection"]'::jsonb, '["Google Maps", "HomeAdvisor", "Storm chaser lists"]'::jsonb),
(5, 'Water Damage / Restoration', NULL, '["24/7 emergencies", "Insurance-driven", "Time-sensitive"]'::jsonb, '["Immediate response required", "Insurance documentation", "Mitigation urgency"]'::jsonb, '["Emergency dispatch", "Insurance info capture", "Damage assessment"]'::jsonb, '["Google Maps", "Insurance referral networks", "Restoration directories"]'::jsonb),
(6, 'Locksmiths', NULL, '["Pure emergency", "24/7 critical", "Immediate need"]'::jsonb, '["All calls urgent", "Location accuracy critical", "Scam competition"]'::jsonb, '["Immediate dispatch", "Location verification", "Price transparency"]'::jsonb, '["Google Maps", "Yelp", "Local directories"]'::jsonb),
(7, 'Towing', NULL, '["24/7 emergency", "Location-based", "Immediate dispatch"]'::jsonb, '["Call volume spikes", "Location accuracy", "ETA expectations"]'::jsonb, '["Emergency dispatch", "Location capture", "ETA communication"]'::jsonb, '["Google Maps", "AAA networks", "Insurance referrals"]'::jsonb),
(8, 'Auto Repair', NULL, '["Repeat customers", "Diagnostic needs", "Parts ordering"]'::jsonb, '["Phone interruptions during repairs", "Estimate follow-ups", "Parts availability"]'::jsonb, '["Appointment scheduling", "Status updates", "Estimate delivery"]'::jsonb, '["Google Maps", "Yelp", "CarFax shop listings"]'::jsonb),
(9, 'Tree Services', NULL, '["Storm emergencies", "Seasonal demand", "Large jobs"]'::jsonb, '["Storm call surges", "Estimate scheduling", "Emergency removals"]'::jsonb, '["Emergency triage", "Estimate booking", "Seasonal scheduling"]'::jsonb, '["Google Maps", "HomeAdvisor", "Arborist directories"]'::jsonb),
(10, 'Garage Door Repair', NULL, '["Emergency lockouts", "Safety issues", "Quick repairs"]'::jsonb, '["Emergency calls", "Same-day requests", "Parts availability"]'::jsonb, '["Emergency dispatch", "Same-day booking", "Parts inquiry handling"]'::jsonb, '["Google Maps", "HomeAdvisor", "Local directories"]'::jsonb),
(11, 'Appliance Repair', NULL, '["Urgent home needs", "Brand-specific", "Parts ordering"]'::jsonb, '["Appliance identification", "Parts availability", "Scheduling windows"]'::jsonb, '["Appliance intake", "Scheduling", "Parts inquiry"]'::jsonb, '["Google Maps", "Yelp", "Manufacturer referrals"]'::jsonb),
(12, 'Pest Control', NULL, '["Urgent infestations", "Recurring services", "Seasonal peaks"]'::jsonb, '["Emergency pest calls", "Recurring scheduling", "Treatment questions"]'::jsonb, '["Infestation triage", "Appointment booking", "Treatment info"]'::jsonb, '["Google Maps", "HomeAdvisor", "Pest control directories"]'::jsonb),
(13, 'Junk Removal', NULL, '["Immediate need", "Volume-based pricing", "Scheduling flexibility"]'::jsonb, '["Quote requests", "Scheduling", "Item descriptions"]'::jsonb, '["Item intake", "Quote estimates", "Scheduling"]'::jsonb, '["Google Maps", "Yelp", "Local directories"]'::jsonb),
(14, 'Bail Bonds', NULL, '["24/7 emergency", "Time-critical", "Legal compliance"]'::jsonb, '["Immediate response required", "Jail information", "Payment processing"]'::jsonb, '["Emergency intake", "Jail info collection", "Process explanation"]'::jsonb, '["Google Maps", "Jail directories", "Legal referrals"]'::jsonb),
(15, 'Criminal Defense Attorneys', NULL, '["Urgent arrests", "Time-sensitive", "High-value cases"]'::jsonb, '["After-hours arrests", "Intake information", "Urgency assessment"]'::jsonb, '["Emergency intake", "Case triage", "Consultation booking"]'::jsonb, '["Google Maps", "Avvo", "Bar association"]'::jsonb),
(16, 'Personal Injury Attorneys', NULL, '["High case value", "Time-sensitive", "Lead qualification"]'::jsonb, '["Lead qualification", "Case intake", "Follow-up timing"]'::jsonb, '["Case intake", "Qualification questions", "Consultation booking"]'::jsonb, '["Google Maps", "Avvo", "Legal directories"]'::jsonb),
(17, 'Dentists', NULL, '["Emergency pain", "Appointment scheduling", "Recurring patients"]'::jsonb, '["Emergency calls", "Appointment scheduling", "Insurance questions"]'::jsonb, '["Emergency triage", "Appointment booking", "Insurance verification"]'::jsonb, '["Google Maps", "Zocdoc", "Dental directories"]'::jsonb),
(18, 'Property Management', NULL, '["Tenant emergencies", "Maintenance requests", "24/7 needs"]'::jsonb, '["After-hours emergencies", "Maintenance coordination", "Tenant communication"]'::jsonb, '["Emergency triage", "Maintenance intake", "Tenant routing"]'::jsonb, '["Google Maps", "Property management directories", "Real estate networks"]'::jsonb),
(19, 'Moving Companies', NULL, '["Quote requests", "Scheduling critical", "High ticket"]'::jsonb, '["Quote complexity", "Scheduling coordination", "Inventory intake"]'::jsonb, '["Quote intake", "Inventory collection", "Scheduling"]'::jsonb, '["Google Maps", "Yelp", "Moving directories"]'::jsonb),
(20, 'Concrete / Masonry', NULL, '["Project-based", "Weather-dependent", "Estimate-driven"]'::jsonb, '["Estimate requests", "Project scheduling", "Weather delays"]'::jsonb, '["Project intake", "Estimate booking", "Weather communication"]'::jsonb, '["Google Maps", "HomeAdvisor", "Contractor directories"]'::jsonb),

-- HOME & PROPERTY SERVICES (21–50)
(21, 'Septic Services', 'Plumbing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(22, 'Well Pump Services', 'Plumbing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(23, 'Gutter Installation & Cleaning', 'Roofing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(24, 'Window Installation', 'Roofing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(25, 'Door Installation', 'Garage Door Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(26, 'Vinyl Siding Contractors', 'Roofing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(27, 'Insulation Contractors', 'HVAC', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(28, 'Chimney Services', 'Roofing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(29, 'Chimney Cleaning', 'Chimney Services', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(30, 'Basement Waterproofing', 'Water Damage / Restoration', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(31, 'Foundation Repair', 'Concrete / Masonry', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(32, 'Solar Installation', 'Electricians', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(33, 'Home Automation', 'Electricians', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(34, 'Security System Installers', 'Electricians', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(35, 'Fire Alarm Systems', 'Electricians', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(36, 'Elevator Repair (Residential)', 'Appliance Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(37, 'Pressure Washing', 'Junk Removal', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(38, 'Window Cleaning', 'Junk Removal', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(39, 'Carpet Cleaning', 'Junk Removal', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(40, 'Air Duct Cleaning', 'HVAC', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(41, 'Mold Remediation', 'Water Damage / Restoration', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(42, 'Biohazard Cleanup', 'Water Damage / Restoration', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(43, 'Hoarding Cleanup', 'Junk Removal', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(44, 'Flooring Contractors', 'Concrete / Masonry', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(45, 'Painting Contractors', 'Roofing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(46, 'Handyman Services', 'Appliance Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(47, 'Fence Installation', 'Concrete / Masonry', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(48, 'Deck Builders', 'Concrete / Masonry', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(49, 'Pool Cleaning & Repair', 'Pest Control', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(50, 'Lawn Care & Landscaping', 'Pest Control', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),

-- AUTOMOTIVE & TRANSPORT (51–65)
(51, 'Mobile Mechanics', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(52, 'Transmission Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(53, 'Auto Body / Collision Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(54, 'Tire Shops', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(55, 'Motorcycle Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(56, 'RV Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(57, 'Boat Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(58, 'Fleet Vehicle Maintenance', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(59, 'Roadside Assistance', 'Towing', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(60, 'Heavy Equipment Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(61, 'Diesel Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(62, 'Car Detailing', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(63, 'Auto Glass Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(64, 'Trailer Repair', 'Auto Repair', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(65, 'Parking Lot Striping', 'Concrete / Masonry', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),

-- PROFESSIONAL SERVICES (66–80)
(66, 'Family Law Attorneys', 'Criminal Defense Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(67, 'Estate Planning Attorneys', 'Criminal Defense Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(68, 'Immigration Attorneys', 'Criminal Defense Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(69, 'Bankruptcy Attorneys', 'Criminal Defense Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(70, 'Real Estate Attorneys', 'Criminal Defense Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(71, 'Accounting Firms', 'Personal Injury Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(72, 'Bookkeepers', 'Accounting Firms', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(73, 'Tax Preparers', 'Accounting Firms', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(74, 'Financial Advisors', 'Personal Injury Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(75, 'Insurance Agencies', 'Personal Injury Attorneys', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(76, 'Mortgage Brokers', 'Property Management', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(77, 'Real Estate Brokerages', 'Property Management', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(78, 'Home Inspectors', 'Property Management', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(79, 'Title Companies', 'Property Management', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(80, 'Appraisal Services', 'Property Management', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),

-- MEDICAL & COMPLIANCE-AWARE (81–92)
(81, 'Chiropractors', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(82, 'Physical Therapy Clinics', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(83, 'Urgent Care Clinics', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(84, 'Mental Health Practices', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(85, 'Addiction Treatment Centers', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(86, 'Dermatology Clinics', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(87, 'Orthopedic Clinics', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(88, 'Imaging Centers', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(89, 'Vision Centers / Optometrists', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(90, 'Hearing Aid Clinics', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(91, 'Massage / Wellness Clinics (Non-Medical)', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(92, 'Senior Care Services', 'Property Management', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),

-- PERSONAL, EDUCATION & MISC (93–100)
(93, 'Hair Salons', 'Dentists', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(94, 'Barber Shops', 'Hair Salons', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(95, 'Nail Salons', 'Hair Salons', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(96, 'Tattoo Studios', 'Hair Salons', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(97, 'Fitness Studios', 'Hair Salons', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(98, 'Martial Arts Schools', 'Fitness Studios', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(99, 'Dance Studios', 'Fitness Studios', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
(100, 'Music Schools', 'Fitness Studios', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb);